-- Seeds the D1 products/merchants tables with the app's previously-hardcoded
-- static demo catalog (android MarketplaceModels.kt: featuredCatalog,
-- discoveryCatalog, fakeFlashDeals, merchCatalog, foodAndCoffeeCatalog),
-- so it becomes admin-editable and Android can be switched to fetch it from
-- the backend instead of a compiled-in list.

INSERT INTO merchants (name, slug, category, description) VALUES ('Ghost Cart Demo Catalog', 'ghost-cart-demo-catalog', 'General', 'Simulated everyday almost-buys used to demo the app - not real products or retail offers.');
INSERT INTO merchants (name, slug, category, description) VALUES ('Ghost Cart Merch', 'ghost-cart-merch', 'Merchandise', 'Simulated Ghost Cart-branded merchandise catalog used to demo the app - not real purchasable merchandise.');

INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Spanish Latte', 'spanish-latte', '', 'Food & Coffee', 3800, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Midnight Burger Meal', 'midnight-burger-meal', '', 'Delivery', 7500, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Luxury Perfume Blind Buy', 'luxury-perfume-blind-buy', 'Almost bought because of a TikTok review?', 'Beauty', 42000, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'White Sneakers', 'white-sneakers', '', 'Fashion', 54900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Studio Headphones', 'studio-headphones', '', 'Music', 89900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Minimal Smartwatch', 'minimal-smartwatch', '', 'Jewellery', 74900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Gaming Tablet Mini', 'gaming-tablet-mini', '', 'Gaming', 129900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Wireless Earbuds', 'wireless-earbuds', '', 'Gadgets & Tech', 39900, 1, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Smartwatch Pro', 'smartwatch-pro', '', 'Gadgets & Tech', 69900, 1, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Tablet Mini 6', 'tablet-mini-6', '', 'Gadgets & Tech', 119900, 1, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Noise Cancelling Headphones', 'noise-cancelling-headphones', '', 'Gadgets & Tech', 27900, 1, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Phone Case', 'ghost-cart-phone-case', '', 'Electronics', 8900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Laptop Sleeve', 'ghost-cart-laptop-sleeve', '', 'Electronics', 14900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Travel Tumbler', 'ghost-cart-travel-tumbler', '', 'Home', 9500, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Classic Cap', 'ghost-cart-classic-cap', '', 'Apparel', 7900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Tote Bag', 'ghost-cart-tote-bag', '', 'Apparel', 6900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Steel Bottle', 'ghost-cart-steel-bottle', '', 'Home', 10900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Notebook', 'ghost-cart-notebook', '', 'Home', 4900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Pen', 'ghost-cart-pen', '', 'Home', 2900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Ceramic Mug', 'ghost-cart-ceramic-mug', '', 'Home', 5900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Lunch Box', 'ghost-cart-lunch-box', '', 'Home', 11900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Running Sneakers', 'ghost-cart-running-sneakers', '', 'Apparel', 24900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Logo T-Shirt', 'ghost-cart-logo-t-shirt', '', 'Apparel', 9900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Protein Shaker', 'ghost-cart-protein-shaker', '', 'Home', 7900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Backpack', 'ghost-cart-backpack', '', 'Apparel', 18900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Bucket Hat', 'ghost-cart-bucket-hat', '', 'Apparel', 8900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Minimal Watch', 'ghost-cart-minimal-watch', '', 'Electronics', 29900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Gym Duffel', 'ghost-cart-gym-duffel', '', 'Apparel', 22900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Supplement Jar', 'ghost-cart-supplement-jar', '', 'Home', 14900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Logo Hoodie', 'ghost-cart-logo-hoodie', '', 'Apparel', 18900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-merch'), 'Ghost Cart Beanie', 'ghost-cart-beanie', '', 'Apparel', 6900, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Midnight Burger Meal', 'midnight-burger-meal-2', '', 'Fast Food', 7500, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Blackout Burger Combo', 'blackout-burger-combo', '', 'Fast Food', 7500, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Coffee & Croissant Combo', 'coffee-croissant-combo', '', 'Coffee & Drinks', 3600, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Ghost Cappuccino', 'ghost-cappuccino', '', 'Coffee & Drinks', 2200, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Pizza Combo', 'pizza-combo', '', 'Fast Food', 9500, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Acai Bowl', 'acai-bowl', '', 'Healthy', 5500, 0, 0, 1);
INSERT INTO products (merchant_id, name, slug, description, category, price_cents, is_flash_deal, is_most_ghosted, is_active) VALUES ((SELECT id FROM merchants WHERE slug = 'ghost-cart-demo-catalog'), 'Spanish Latte', 'spanish-latte-2', '', 'Coffee & Drinks', 3800, 0, 0, 1);
